# Start window numbering at 1 (not 0)
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse support
set -g mouse on

# Increase history limit
set -g history-limit 10000

# 256 color & TrueColor support
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'
set -as terminal-features ',xterm-256color:clipboard'

# Status bar position
set-option -g status-position top

# Set the entire status bar background to transparent
set -g status-style bg=default

# Set the default text color for the window list (foreground)
set -g status-fg colour244

# Change the appearance of the ACTIVE window
set-window-option -g window-status-current-style fg=yellow,bg=default

# Style non-active windows
set-window-option -g window-status-style fg=colour244,bg=default

# Faster escape sequences for Neovim modal switching
set -sg escape-time 10

# Permission to pass terminal escape sequences through to Windows
set -s set-clipboard on
set -g allow-passthrough on
